import type { Mission, Vehicle } from '../../types/domain'
export const vehicles: Vehicle[] = [
  {
    id: 'UAV-001',
    name: 'Falcon Alpha',
    type: 'UAV',
    status: 'online',
    health: 'healthy',
    battery: 82,
    protocol: 'MAVLink',
    controller: 'PX4',
    connection: 'RF + 4G',
    mode: 'AUTO',
    mission: 'Coastal Sweep',
    lastSeen: 'Now',
    lat: 53,
    lng: 61,
    heading: 38,
    speed: 18.4,
    link: 94,
    capabilities: ['goto', 'manualControl', 'takeoff', 'land', 'returnHome', 'video', 'thermal'],
  },
  {
    id: 'UAV-002',
    name: 'Falcon Bravo',
    type: 'UAV',
    status: 'online',
    health: 'warning',
    battery: 47,
    protocol: 'MAVLink',
    controller: 'ArduPilot',
    connection: 'RF',
    mode: 'LOITER',
    mission: 'Standby',
    lastSeen: '2s',
    lat: 69,
    lng: 31,
    heading: 120,
    speed: 3.2,
    link: 68,
    capabilities: ['goto', 'takeoff', 'land', 'returnHome', 'video'],
  },
  {
    id: 'UGV-001',
    name: 'Rover Alpha',
    type: 'UGV',
    status: 'online',
    health: 'healthy',
    battery: 76,
    protocol: 'DDS',
    controller: 'ROS 2 / Nav2',
    connection: '5G',
    mode: 'AUTONOMOUS',
    mission: 'Perimeter',
    lastSeen: 'Now',
    lat: 38,
    lng: 46,
    heading: 275,
    speed: 5.8,
    link: 91,
    capabilities: ['goto', 'manualControl', 'hold', 'returnBase', 'lidar'],
  },
  {
    id: 'UGV-002',
    name: 'Rover Bravo',
    type: 'UGV',
    status: 'offline',
    health: 'critical',
    battery: 12,
    protocol: 'MAVLink',
    controller: 'ArduPilot Rover',
    connection: 'RF',
    mode: 'SAFE',
    mission: '—',
    lastSeen: '18m',
    lat: 25,
    lng: 72,
    heading: 190,
    speed: 0,
    link: 0,
    capabilities: ['goto', 'manualControl', 'hold', 'returnBase'],
  },
  {
    id: 'USV-001',
    name: 'Marine Alpha',
    type: 'USV',
    status: 'online',
    health: 'healthy',
    battery: 64,
    protocol: 'MAVLink',
    controller: 'ArduPilot',
    connection: 'LTE + SAT',
    mode: 'AUTO',
    mission: 'Harbor Watch',
    lastSeen: 'Now',
    lat: 76,
    lng: 76,
    heading: 218,
    speed: 8.1,
    link: 88,
    capabilities: ['goto', 'manualControl', 'hold', 'returnBase', 'radar', 'sonar'],
  },
  {
    id: 'UUV-001',
    name: 'Abyss Alpha',
    type: 'UUV',
    status: 'warning',
    health: 'warning',
    battery: 58,
    protocol: 'MAVLink',
    controller: 'ArduSub',
    connection: 'ACOUSTIC',
    mode: 'DEPTH HOLD',
    mission: 'Reef Scan',
    lastSeen: '6s',
    lat: 57,
    lng: 82,
    heading: 312,
    speed: 2.4,
    link: 61,
    capabilities: ['goto', 'dive', 'surface', 'hold', 'sonar'],
  },
]
export const missions: Mission[] = [
  {
    id: 'MSN-204',
    name: 'Coastal Sweep',
    vehicleId: 'UAV-001',
    status: 'executing',
    progress: 63,
    waypoints: [
      { id: 'WP-01', latitude: 23.77, longitude: 90.38, altitude: 120 },
      { id: 'WP-02', latitude: 23.79, longitude: 90.41, altitude: 180 },
      { id: 'WP-03', latitude: 23.76, longitude: 90.44, altitude: 150 },
    ],
  },
  {
    id: 'MSN-211',
    name: 'Perimeter',
    vehicleId: 'UGV-001',
    status: 'executing',
    progress: 41,
    waypoints: [
      { id: 'WP-01', latitude: 23.8, longitude: 90.36 },
      { id: 'WP-02', latitude: 23.802, longitude: 90.362 },
      { id: 'WP-03', latitude: 23.801, longitude: 90.364 },
    ],
  },
  {
    id: 'MSN-198',
    name: 'Harbor Watch',
    vehicleId: 'USV-001',
    status: 'executing',
    progress: 38,
    waypoints: [],
  },
]
